/// Flutter icons Hide
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Hide
///      fonts:
///       - asset: fonts/Hide.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Hide {
  Hide._();

  static const _kFontFam = 'Hide';
  static const String? _kFontPkg = null;

  static const IconData hidden = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
