/// Flutter icons Image
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Image
///      fonts:
///       - asset: fonts/Image.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Images {
  Images._();

  static const _kFontFam = 'Image';
  static const String? _kFontPkg = null;

  static const IconData image = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
