/// Flutter icons Loupe
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Loupe
///      fonts:
///       - asset: fonts/Loupe.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Loupe {
  Loupe._();

  static const _kFontFam = 'Loupe';
  static const String? _kFontPkg = null;

  static const IconData loupe = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
