/// Flutter icons Pencil
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Pencil
///      fonts:
///       - asset: fonts/Pencil.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Pencil {
  Pencil._();

  static const _kFontFam = 'Pencil';
  static const String? _kFontPkg = null;

  static const IconData pencil = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
