/// Flutter icons Person
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Person
///      fonts:
///       - asset: fonts/Person.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Person {
  Person._();

  static const _kFontFam = 'Person';
  static const String? _kFontPkg = null;

  static const IconData account_circle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
